spring.application.name=bookstore

spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_db
spring.datasource.username=postgres
spring.datasource.password=Temp@123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.level.org.hibernate.springframework=info

logging.level.com.tss.bookstore=DEBUG
logging.level.root=info

logging.file.path=.